<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@yield('title', 'NCAT FMD Document')</title>
    <style>
        @page { margin: 22px 26px; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 9.5px; color: #101318; margin: 0; }
        .crest { height: 46px; }
        .doc-head { width: 100%; border-collapse: collapse; margin-bottom: 6px; }
        .doc-head td { vertical-align: middle; }
        .org { text-align: center; }
        .org .name { font-size: 14px; font-weight: bold; color: #101A62; letter-spacing: .5px; }
        .org .dept { font-size: 10.5px; font-weight: bold; letter-spacing: 2px; }
        .org .title { font-size: 11px; font-weight: bold; margin-top: 2px; text-transform: uppercase; }
        .org .sub { font-size: 8.5px; color: #353A45; }
        .rule { border: none; border-top: 2px solid #101A62; margin: 4px 0 8px; }
        table.grid { width: 100%; border-collapse: collapse; }
        table.grid td, table.grid th { border: 1px solid #101A62; padding: 3px 5px; vertical-align: top; }
        .lbl { font-size: 7px; text-transform: uppercase; letter-spacing: .4px; color: #353A45; display: block; margin-bottom: 2px; }
        .val { font-size: 10px; min-height: 14px; }
        .num { font-weight: bold; color: #101A62; }
        .section-bar { background: #101A62; color: #fff; font-size: 8.5px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; padding: 3px 6px; margin: 8px 0 0; }
        .sign-line { border-bottom: 1px solid #353A45; height: 20px; }
        .foot-note { font-size: 7.5px; color: #353A45; margin-top: 8px; }
        .distribution { font-size: 8px; font-weight: bold; text-align: center; margin-top: 6px; letter-spacing: .5px; }
        table.lines { width: 100%; border-collapse: collapse; }
        table.lines th { background: #101A62; color: #fff; font-size: 7.5px; text-transform: uppercase; padding: 4px; border: 1px solid #101A62; }
        table.lines td { border: 1px solid #6b7280; padding: 3px 4px; font-size: 9px; }
        .r { text-align: right; }
        .c { text-align: center; }
        .muted { color: #737B89; }
        .badge { display: inline-block; border: 1px solid #101A62; border-radius: 3px; padding: 1px 6px; font-size: 8px; font-weight: bold; color: #101A62; text-transform: uppercase; }
    </style>
</head>
<body>
    <table class="doc-head">
        <tr>
            <td style="width: 60px;"><img src="{{ $crest }}" class="crest" alt="NCAT"></td>
            <td class="org">
                <div class="name">NIGERIAN COLLEGE OF AVIATION TECHNOLOGY, ZARIA</div>
                <div class="dept">FLIGHT MAINTENANCE DEPARTMENT</div>
                <div class="title">@yield('form-title')</div>
                @hasSection('form-sub')<div class="sub">@yield('form-sub')</div>@endif
            </td>
            <td style="width: 60px; text-align: right;">
                @hasSection('doc-no')<span class="badge">@yield('doc-no')</span>@endif
            </td>
        </tr>
    </table>
    <hr class="rule">

    @yield('body')

    <div class="foot-note">Generated by the NCAT FMD Inventory System · {{ now()->format('d M Y H:i') }} · Signatures to be completed in wet ink on the printed copy.</div>
</body>
</html>
